---

- name: Install google chrome
  dnf: name=https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm state=present

- name: Install vivaldi
  dnf: name=https://downloads.vivaldi.com/stable/vivaldi-stable-1.3.551.30-1.x86_64.rpm state=present

...
